Add options to support doing luis and qna cross-train seperately
microsoft/botframework-cli pull request #1161
Opened 2021-03-17 10:04 UTC by cosmicshuai

--omitLuis: cross-train will skip luis cross-train
--omitQna: cross-train will skip qna cross-train

2021-03-17 10:08 UTC, boydc2014 commented on packages/lu/src/parser/cross-train/cross-train.js
> +  train: async function (input, intentName, config, verbose, omitLuis, omitQna) {
It might be good to
rename omitLuis to inner-dialog
rename omitQna to intra-dialog 

and include inner-dialog, intra-dialog into one object called options maybe

2021-03-17 11:38 UTC, cosmicshuai commented on packages/lu/src/parser/cross-train/cross-train.js
> +  train: async function (input, intentName, config, verbose, omitLuis, omitQna) {
changed the naming and merged into one object during function call

2021-03-17 11:42 UTC, feich-ms commented on packages/lu/src/parser/cross-train/cross-train.js
> +  train: async function (input, intentName, config, verbose, enrichDialogOpt) {
add descriptions at function header above

2021-03-17 11:42 UTC, feich-ms commented on packages/lu/src/parser/cross-train/crossTrainer.js
> +   * @param {any} options some optional parameters including configId, intentName, verbose, importResolver, luOnly
remove this

2021-03-17 11:45 UTC, feich-ms commented on packages/lu/src/parser/cross-train/crossTrainer.js
> +        options.enrichDialogOpt)
add a default value for enrichDialogOpt, otherwise it will be breaking changes

2021-03-17 11:47 UTC, feich-ms commented on packages/lu/test/parser/cross-train/crossTrainer.test.js
> +    assert.isTrue(qnaContent.includes('# DeferToRecognizer_') === false)
Add assert for inner dialog cross-train, e.g. assert _Interruption intent

2021-03-17 12:04 UTC, feich-ms commented on packages/lu/test/parser/cross-train/crossTrainer.test.js
> +    assert.isTrue(qnaContent.includes('# DeferToRecognizer_') === false)
Add test for {inner: false, intra: true}

2021-03-17 12:05 UTC, feich-ms commented on packages/luis/test/commands/luis/crossTrain.test.ts
> +      '--inner_dialog'])
Add test for --intra_dialog

2021-03-17 12:06 UTC, feich-ms commented on packages/luis/src/commands/luis/cross-train.ts
> +    inner_dialog: flags.boolean({description: 'Only do inner dialog cross train', default: false}),
maybe rename to innerDialog and intraDialog?

2021-03-17 12:07 UTC, feich-ms commented on packages/luis/src/commands/luis/cross-train.ts
> +    inner_dialog: flags.boolean({description: 'Only do inner dialog cross train', default: false}),
Please also add these newly added parameter descriptions to README files in luis folder and cli folder

2021-03-18 06:34 UTC, boydc2014 commented on packages/lu/src/parser/cross-train/cross-train.js
> +  train: async function (input, intentName, config, verbose, enrichDialogOpt) {
trainOpts/trainerOptions

2021-03-18 06:57 UTC, cosmicshuai commented on packages/lu/src/parser/cross-train/cross-train.js
> +  train: async function (input, intentName, config, verbose, enrichDialogOpt) {
renamed to trainingOpt

2021-03-18 06:57 UTC, cosmicshuai commented on packages/lu/src/parser/cross-train/crossTrainer.js
> +   * @param {any} options some optional parameters including configId, intentName, verbose, importResolver, luOnly
removed

2021-03-18 06:57 UTC, cosmicshuai commented on packages/lu/src/parser/cross-train/crossTrainer.js
> +        options.enrichDialogOpt)
added

2021-03-18 06:58 UTC, cosmicshuai commented on packages/lu/test/parser/cross-train/crossTrainer.test.js
> +    assert.isTrue(qnaContent.includes('# DeferToRecognizer_') === false)
added assert and test for  {inner: false, intra: true} case

2021-03-18 06:58 UTC, cosmicshuai commented on packages/luis/src/commands/luis/cross-train.ts
> +    inner_dialog: flags.boolean({description: 'Only do inner dialog cross train', default: false}),
added

2021-03-18 06:59 UTC, feich-ms commented
@munozemilio could you please help to approve this PR since it will be used by composer

2021-03-18 07:02 UTC, feich-ms commented on packages/luis/README.md
> +  --innerDialog            Only perform the inner dialog cross train
pls also add this to the README in cli package

2021-03-18 07:10 UTC, cosmicshuai commented on packages/luis/README.md
> +  --innerDialog            Only perform the inner dialog cross train
added

2021-03-18 07:10 UTC, cosmicshuai commented on packages/luis/test/commands/luis/crossTrain.test.ts
> +      '--inner_dialog'])
added

2021-03-18 14:24 UTC, boydc2014 commented
cc @scheyal this is the cli part that allows us to do finer-grain control of cross-train. Once this is taken, we can leverage this in Composer side.

2021-03-22 03:25 UTC, feich-ms approved these changes

2021-03-22 03:40 UTC, munozemilio commented on packages/luis/src/commands/luis/cross-train.ts
> +    innerDialog: flags.boolean({description: 'Only do inner dialog cross train', default: false}),
From customer usability perspective I have learned that using dashes rather than camel case its more readable. I understand we have a bunch of camelcase flags but  it may be a good idea to switch to inner-dialog, intra-dialog and luis-recognizer-id

2021-03-22 03:42 UTC, munozemilio commented on packages/luis/src/commands/luis/cross-train.ts
> +      if (flags.luRecognizerID !== 'Luis' && flags.luRecognizerID !== 'Orchestrator') {
you can add options to the flag definition.

```
static flags = {
  name: flags.string({
    char: 'n',                    // shorter flag version
    description: 'name to print', // help description for flag
    hidden: false,                // hide from help
    multiple: false,              // allow setting this flag multiple times
    env: 'MY_NAME',               // default to value of environment variable
    options: ['a', 'b'],          // only allow the value to be from a discrete set
    parse: input => 'output',     // instead of the user input, return a different value
    default: 'world',             // default value if flag not passed (can be a function that returns a string or undefined)
    required: false,              // make flag required (this is not common and you should probably use an argument instead)
    dependsOn: ['extra-flag'],    // this flag requires another flag
    exclusive: ['extra-flag'],    // this flag cannot be specified alongside this other flag
  }),
```

2021-03-22 03:48 UTC, munozemilio commented on packages/luis/src/commands/luis/cross-train.ts
> +        trainingOpt = {
Since innerDialog and intraDialog have default to false you can set the object only once and void code duplication.

2021-03-22 03:48 UTC, munozemilio approved these changes
I left some comments.

2021-03-22 05:36 UTC, munozemilio requested changes
CIL

2021-03-22 05:36 UTC, munozemilio commented
/azp run

2021-03-22 07:28 UTC, cosmicshuai commented on packages/luis/src/commands/luis/cross-train.ts
> +    innerDialog: flags.boolean({description: 'Only do inner dialog cross train', default: false}),
naming changed

2021-03-22 07:28 UTC, cosmicshuai commented on packages/luis/src/commands/luis/cross-train.ts
> +      if (flags.luRecognizerID !== 'Luis' && flags.luRecognizerID !== 'Orchestrator') {
added options

2021-03-22 07:28 UTC, cosmicshuai commented on packages/luis/src/commands/luis/cross-train.ts
> +        trainingOpt = {
remove dup code

2021-03-22 07:57 UTC, boydc2014 commented
1. I think those two flags should be set to true by default, it should not be a requirement to learn and set those flags in normal case
2. the lu-recognizer-id and qna-recognizer-id, should not apply to the whole cross-train process, it should be applied per dialog, thus, probably it should in the config.json instead of in the options.

2021-03-22 09:27 UTC, boydc2014 commented on packages/cli/README.md
> +  --luRecognizerID         Recognizer ID of language understanding, shoule be one of Luis or Orchestrator, default is Luis
cli should not expose luRecognizerID

2021-03-22 11:27 UTC, cosmicshuai commented on packages/cli/README.md
> +  --luRecognizerID         Recognizer ID of language understanding, shoule be one of Luis or Orchestrator, default is Luis
remove lu-recognizer-id

2021-03-22 17:52 UTC, munozemilio approved these changes

2021-03-23 02:01 UTC, merged